version: "3.7"

services:
    freeipa:
    image: freeipa/freeipa-server:centos-8-4.9.6
    restart: unless-stopped
    hostname: $HOSTNAME
    environment:
      IPA_SERVER_HOSTNAME: $HOSTNAME
      TZ: "America/Toronto"
    tty: true
    stdin_open: true
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - freeipavol:/data
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
    security_opt:
      - "seccomp:unconfined"
    environment:
      - DOMAIN=devopsdaydayup.org
      - REALM=devopsdaydayup.org
      - IPA_HOSTNAME=ipa.devopsdaydayup.org
      - IPA_PASSWORD=admin123
    command:
      - --no-host-dns
      - --unattended
    ports:
      - "53:53/udp"
      - "53:53"
      - "80:80"
      - "443:443"
      - "389:389"
      - "636:636"
      - "88:88"
      - "464:464"
      - "88:88/udp"
      - "464:464/udp"
      - "123:123/udp"
      - "7389:7389"
      - "9443:9443"
      - "9444:9444"
      - "9445:9445"

    vault:
    build:
      context: .
      dockerfile: vault.Dockerfile
    cap_add:
      - IPC_LOCK
    volumes:
      - type: volume
        source: vault_file
        target: /vault/file
      - type: volume
        source: vault_config
        target: /vault/config
    depends_on:
      - freeipa
    ports:
      - '8200:8200'

    nexus:
    image: sonatype/nexus3
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
  
    jenkins:
    build:
      context: .
      dockerfile: jenkinsplugin.Dockerfile
    user: root
    privileged: true
    ports:
      - '8080:8080'
      - '50000:50000'
    environment:
      # Please update JENKINS_PASSWORD and JENKINS_USERNAME in .env file
      - JENKINS_USER=root
      - TZ=America/Toronto
      - JENKINS_ADMIN_ID=$JENKINS_USERNAME
      - JENKINS_ADMIN_PASSWORD=$JENKINS_PASSWORD
    volumes:
      - 'jenkins_data:/var/jenkins_home'
      - '/usr/bin/docker:/usr/bin/docker'
      - '/var/run/docker.sock:/var/run/docker.sock'
  
    tomcat:
    image: tomcat:8.5-jdk15-openjdk-oracle
    restart: always
    container_name: tomcat
    hostname: tomcat
    ports:
      - '8090:8080'
    user: root       
    environment:
      - TOMCAT_USERNAME=yong
      - TOMCAT_PASSWORD=123456
      - TOMCAT_ALLOW_REMOTE_MANAGEMENT=yes        
    volumes:
      - /etc/localtime:/etc/localtime
      - ./webapps:/usr/local/tomcat/webapps 
      - ./logs:/usr/local/tomcat/logs

volumes:
  nexus-data: 
    driver: local
  jenkins_data:
    driver: local
  freeipavol:
    driver: local
  vault_file:
    driver: local
  vault_config:
    driver: local

